### ISSUE TITLE
Member count and prune missing in server settings

### ISSUE THREAD

**Issue by mfsoup** [ObserverOfTime/DiscordThemes#1]
![gc7f8d](https://user-images.githubusercontent.com/38110452/38378939-3428570c-38cd-11e8-9ea4-c96391bdf015.png)

This appears to be missing in server settings > members.

**Comment by ObserverOfTime** [comment]
I can see it on my end. Are you sure it's not another theme, plugin or custom CSS that's causing it?

**Comment by mfsoup** [comment]
Not sure what the problem was but updating to V1.2.1 with the same CSS/plugins fixed it. Thanks!
