### ISSUE TITLE
Discord Web bug

### ISSUE THREAD

**Issue by Mioni** [ObserverOfTime/DiscordThemes#6]
## Current Behavior
It's all black I think it has updated Discord and misconfigured the theme.

## Your Environment

* Version used: 1.6.1
* Operating System and version: Windows 10
* Browser name and version (for the web theme): Vivaldi 2.8

**Comment by ObserverOfTime** [comment]
Yeah, the new Discord update broke it and I haven't had the time to fix it yet.
