### ISSUE TITLE
Unnecesary button hiding

### ISSUE THREAD

**Issue by Alulululululu** [ObserverOfTime/DiscordThemes#9]
The NewNihilism theme hides the gift and gif button, but this isn't needed as there's already options in BetterDiscord that do that.

**Comment by ObserverOfTime** [comment]
It was needed because the options didn't work for a while. You can disable them for now.

**Comment by ObserverOfTime** [comment]
Fixed in 1a6021be49c7ce3cf59796f4d2771a6a9cefecd9
